server:
  port: 80
  contextPath: /udcs-web
  sessionTimeout: 3000
  tomcat:
    uriEncoding: UTF-8
    compression: on

spring:
  http:
    encoding:
      charset: utf8
      enabled: true
  thymeleaf:
      cache: false
      prefix: classpath:/templates/
      enabled: true
      suffix: .htm
      mode: HTML5
      encoding: UTF-8
      content-type: text/html
  mvc:
    view:
      prefix: lasspath:/templates/
      suffix: .htm

kaptcha:
  session:
    key: kaptcha.code
  border:
    color: 105,179,90
  #渲染效果：水纹：WaterRipple；鱼眼：FishEyeGimpy；阴影：ShadowGimpy
  obscurificator:
    impl: com.google.code.kaptcha.impl.WaterRipple
  #不要噪点
  noise:
    impl: com.google.code.kaptcha.impl.NoNoise
    color: black
  word:
    impl: com.google.code.kaptcha.text.impl.DefaultWordRenderer
  image:
    width: 130
    height: 40
  textproducer:
    font:
      size: 24
      color: green
    char:
      string: 23456789abcdefghjklmnprstuvwxyzABCDEFGHJKLMPQRSTUVWXYZ
      length: 6
      space: 5
  #和登录框背景颜色一致
  background:
    clear:
      from: white
      to: white

## 默认的profile为dev，其他环境通过指定启动参数使用不同的profile，比如：
##  开发环境：java -jar my-spring-boot.jar --spring.profiles.active=local
##  开发环境：java -jar my-spring-boot.jar --spring.profiles.active=dev
##  测试环境：java -jar my-spring-boot.jar --spring.profiles.active=test1/2/3/4/5/6/7/8/9/10/11/12/13/14
##  UAT测试环境：java -jar my-spring-boot.jar --spring.profiles.active=uat1/2/3
##  性能测试环境：java -jar my-spring-boot.jar --spring.profiles.active=perf1/2/3
##  生产环境：java -jar my-spring-boot.jar --spring.profiles.active=prod

---
spring:
  profiles: local
comConfig:
  file: classpath:configs/config.properties
amqConfig:
  file: classpath:configs/amq_config.properties
dbsConfig:
  file: classpath:configs/dbs.properties
logging:
  config: classpath:configs/logback.xml
  path: /home/finance/Logs/udcs